# .github/workflows/create-msi.yml
#
# 2025
# By Pedro Henrique Garcia.
# Github/gitlab: Phkaiser13

name: Create MSI Installer

on:
  push:
    branches: [ "main" ]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do seu repositório.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK 21).
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Executa a tarefa 'installDist' para compilar e agrupar a aplicação.
      - name: Build application distribution with Gradle
        run: ./gradlew.bat :ui:installDist

      # 4. (Passo de Depuração) Lista os arquivos na pasta de distribuição.
      - name: List files in distribution directory
        run: |
          echo "Listing contents of ui/build/install/ui..."
          ls -R ui/build/install/ui
        shell: bash

      # 5. Cria o instalador .msi usando a ferramenta 'jpackage'.
      - name: Create MSI Installer with jpackage
        run: |
          jpackage --type msi `
            --dest release `
            --name JavaCalc `
            --app-version 1.0.0 `
            --vendor "Pedro Henrique Garcia" `
            --input ui/build/install/ui/lib `
            --main-jar ui-1.0.0.jar `
            --main-class com.phg.javacalc.ui.MainApplication `
            --icon ui/src/main/resources/com/phg/javacalc/ui/icon.ico
        shell: powershell

      # 6. Faz o upload do instalador gerado como um "artefato".
      # CORREÇÃO: Atualizado de v3 para v4
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JavaCalc-Installer
          path: release/
