# .github/workflows/create-msi.yml
#
# 2025
# By Pedro Henrique Garcia.
# Github/gitlab: Phkaiser13

# Nome do workflow que aparecerá na aba "Actions" do GitHub.
name: Create MSI Installer

# Gatilho: executa este workflow a cada commit na branch 'main'.
on:
  push:
    branches: [ "main" ]

# Define os trabalhos a serem executados.
jobs:
  build-installer:
    # O trabalho será executado em uma máquina virtual Windows,
    # que é necessário para criar um instalador .msi.
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK 21).
      # Usamos a mesma versão do seu workflow de CI para manter a consistência.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Executa a tarefa 'installDist' do Gradle no módulo 'ui'.
      # Esta tarefa compila a aplicação e agrupa todos os arquivos necessários
      # (seus JARs e as dependências, como o JavaFX) em uma única pasta,
      # pronta para ser empacotada.
      - name: Build application distribution with Gradle
        run: ./gradlew.bat :ui:installDist

      # 4. Cria o instalador .msi usando a ferramenta 'jpackage'.
      # 'jpackage' é uma ferramenta do próprio JDK para criar instaladores nativos.
      - name: Create MSI Installer with jpackage
        run: |
          jpackage --type msi `
            --dest release `
            --name JavaCalc `
            --app-version 1.0.0 `
            --vendor "Pedro Henrique Garcia" `
            --input ui/build/install/ui `
            --main-jar ui-1.0.0.jar `
            --main-class com.phg.javacalc.ui.MainApplication `
            --icon ui/src/main/resources/com/phg/javacalc/ui/icon.ico
        shell: powershell

      # 5. Faz o upload do instalador gerado como um "artefato".
      # Isso permite que você baixe o arquivo .msi diretamente da página
      # de resumo da execução do workflow no GitHub.
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: JavaCalc-Installer
          path: release/
